# Generated by Django 3.2.18 on 2023-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='x',
            new_name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='y',
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(default=78),
            preserve_default=False,
        ),
    ]
